language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일 전송
notifications:
  email:
    recipients:
      - ayaysir0@naver.com


before_deploy:
  - zip -r awsboard *
  - mkdir -p deploy
  - mv awsboard.zip deploy/awsboard.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-awsboard-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    key: awsboard.zip
    bundle_type: zip
    application: awsboard-1
    deployment_group: awsboard-codedeploy-group
    region: ap-northeast-2
    wait-until-deployed: true


